SUPABASE_URL = "https://szmeetqlftgftjnpesbl.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6bWVldHFsZnRnZnRqbnBlc2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjMyOTksImV4cCI6MjA3Mzc5OTI5OX0.pGSuh9OjUh9fqDsFXKFxuNn_tdtiicQ_43sfnDM-kMo"
MODAL_API_BASE = "https://josejuanlazcano123--ml-service-fastapi-app.modal.run"
FEATURE_COLUMNS = "..."